<?php

declare(strict_types=1);

namespace EventPulse\Domain\Notification\ValueObject;

use EventPulse\Domain\Notification\Exception\InvalidNotificationInputException;
use EventPulse\Domain\Shared\UuidGenerator;


/**
 * A string that ties together all log lines, events, and derivative actions
 * caused by a single caller request (domain.md §2).
 *
 * Unlike IdempotencyKey, CorrelationId changes on each submission. It may be:
 *  - supplied by the caller (for end-to-end tracing across systems);
 *  - generated by the application layer when the caller omits it.
 *
 * Format: UUID v4 or a printable ASCII string up to 128 characters.
 * Accepting non-UUID caller-supplied correlation ids is intentional — some
 * callers use their own trace ID formats (e.g. W3C traceparent segments).
 */
final class CorrelationId
{
    private const MAX_LENGTH = 128;

    private function __construct(
        private readonly string $value,
    ) {}

    public static function generate(): self
    {
        return new self(UuidGenerator::generate());
    }

    public static function fromString(string $value): self
    {
        if (strlen($value) === 0 || strlen($value) > self::MAX_LENGTH) {
            throw new InvalidNotificationInputException(
                sprintf('CorrelationId must be 1–%d characters.', self::MAX_LENGTH)
            );
        }

        if (!preg_match('/^[\x21-\x7E]+$/', $value)) {
            throw new InvalidNotificationInputException(
                'CorrelationId must contain only printable ASCII characters.'
            );
        }

        return new self($value);
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function equals(self $other): bool
    {
        return $this->value === $other->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
